const vulnerabilitiesModel = require("../models/vulnerabilityModel.js");

module.exports = {
    addVulnerability: async (req, res) => {
        const {software_name, affected_versions, severity, description, reference_url, reported_date, last_updated, patch_available, wf_id} = req.body;
        try {
            const vulnerability = await vulnerabilitiesModel.createVulnerability(software_name, affected_versions, severity, description, reference_url, reported_date, last_updated, patch_available, wf_id);
            res.status(201).json({
                message: "vulnerability registered successfully",
                vulnerability,
            });            
        } catch (error) {
            console.log(error);
            res.status(500).json({
                message: "Internal Server Error"
            });
        }
    },
    refreshVulnerabilitiesAPI: async (req, res) => {
        try {
            const didUpdate = await vulnerabilitiesModel.dropAndImport();
            if(didUpdate) {
                res.status(201).json({message: "updated vulnerabilities via WF API"})
                return;
            } 
            res.status(500).json({message: "Not really sure what happened. Try later"})
        } catch (error) {
            console.log(error);
            res.status(500).json({
                message: "Internal Server Error"
            });
        }
    },
    getUserVulnerabilities: async (req, res) => {
        const {id} = req.params;

        try {
            const vulnerabilities = await vulnerabilitiesModel.getUserRelevantVulnerabilities(id);
            res.status(200).json(vulnerabilities)
        }catch(error) {
            console.log(error);
            res.status(500).json({
                message: "Internal Server Error"
            });
        }
    },
    getVulnerabilities: async (req, res) => {
        
        try {
            const vulnerabilities = await vulnerabilitiesModel.getAllVulnerabilities();
            res.status(200).json(vulnerabilities)
        }catch(error) {
            console.log(error);
            res.status(500).json({
                message: "Internal Server Error"
            });
        }
    }
}